---Magnitude Analysis-agg(Measure) by dimension----

---Total no.of customers by country---
SELECT country,count(customer_key) AS total_customers from gold.dim_customers GROUP BY country;
---Gender wise Customers---
SELECT gender,count(customer_key) AS total_customers from gold.dim_customers GROUP BY gender ORDER BY gender;
---Total Produts based on category-----
SELECT category,count(product_key) AS total_products from gold.dim_products GROUP BY category;
----Avg cosst in each category---
SELECT category,AVG(cost) AS avg_cost from gold.dim_products GROUP BY category;
----Total Revenue generated for each category--------
SELECT sum(f.sales_amount) as total_revenue,p.category from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key group by category order by total_revenue DESC;

------Total revenue generated by each customer---
SELECT sum(f.sales_amount) as total_revenue,c.customer_key,c.first_name,c.last_name from gold.fact_sales f left join gold.dim_customers c on f.customer_key=c.customer_key group by c.customer_key,c.first_name,c.last_name order by total_revenue DESC;

--distribution of items sold across countries--
SELECT count(f.quantity) as total_items,c.country from gold.fact_sales f left join gold.dim_customers c on f.customer_key=c.customer_key group by c.country order by total_items DESC;

---Ranking Analysis----rank the category based on measure--Top N

SELECT Top 5 p.product_name,sum(f.sales_amount) as Total_revenue from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key group by p.product_name order by sum(f.sales_amount) DESC;

---Ranking Analysis----rank the category based on measure--Bottom N

SELECT Top 5 p.product_name,sum(f.sales_amount) as Total_revenue from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key group by p.product_name order by sum(f.sales_amount);

--Using Window Functions---

Select * from (SELECT SUM(f.sales_amount) as Total_sales,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) as Rank_Flag
,p.product_name from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key group by p.product_name)t where Rank_Flag<=5;

---------Change Over Time Analysis-----
Select Year(order_date) AS ORDER_YEAR,SUM(sales_amount) AS TOTAL_SALES FROM gold.fact_sales WHERE Year(order_date) IS NOT NULL group by Year(order_date) ORDER BY SUM(sales_amount) DESC;

Select datetrunc(YEAR,order_date) AS ORDER_YEAR,SUM(sales_amount) AS TOTAL_SALES FROM gold.fact_sales WHERE datetrunc(YEAR,order_date) IS NOT NULL group by datetrunc(YEAR,order_date) ORDER BY SUM(sales_amount) DESC;

-----------Running Total/Cumulative Analysis--------------

 SELECT TOP 3 * from gold.dim_customers;
select TOP 3 * from gold.dim_products;
select Top 3 * from gold.fact_sales;
--Running total---and  moving_average---
SELECT order_date,total_sales,sum(total_sales) over(order by order_date) AS running_total,
AVG(avg_sales) over(order by order_date) AS moving_average
from
(
SELECT DATETRUNC(YEAR,order_date) AS order_date,
SUM(sales_amount) AS total_sales,
avg(sales_amount) AS avg_sales
from gold.fact_sales 
where DATETRUNC(YEAR,order_date) is not null group by DATETRUNC(YEAR,order_date))t;

------Performace Analysis by comparing current year sales with its avg sales and previous year sales--------
WITH yearly_product_sales AS
(
SELECT p.product_name,
		YEAR(f.order_date) AS order_year,
		SUM(f.sales_amount) AS current_year_sales
		from
		gold.fact_sales f LEFT JOIN gold.dim_products p on f.product_key=p.product_key
		WHERE f.order_date IS NOT NULL
		GROUP BY YEAR(f.order_date),
		p.product_name
		
		
)

select product_name,order_year,current_year_sales,
 AVG(current_year_sales) over(partition by product_name) as avg_sales,
 CASE  
  when current_year_sales-AVG(current_year_sales) over(partition by product_name)> 0 THEN 'ABOVE_AVG'
  when current_year_sales-AVG(current_year_sales) over(partition by product_name)< 0 THEN 'BELOW_AVG'
  ELSE 'AVG'
  END as average_change,
 lag(current_year_sales) over(partition by product_name order by current_year_sales) as py_sales,
 CASE 
 WHEN current_year_sales-lag(current_year_sales) over(partition by product_name order by current_year_sales)>0 THEN 'INCREASING'
 WHEN current_year_sales-lag(current_year_sales) over(partition by product_name order by current_year_sales)<0 THEN 'DECREASING'
 ELSE 'previous_year'
 END AS py_change
 from yearly_product_sales
 order by product_name;

 ----------------------Part to Whole Analysis show which category is contributing more to the overall slaes---------------
 WITH category_sales AS
 (
 SELECT 
 p.category,sum(f.sales_amount) as total_sales from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key
 group by p.category
 )
 SELECT category,total_sales,
 sum(total_sales) over() as overall_sales,
  CONCAT(ROUND((CAST(total_sales AS FLOAT)/sum(total_sales) over())*100,2),'%') as contribution
 
 from category_sales;

 -----------DATA SEGMENTATAION-------
 /* Segment products into cost ranges and 
 count how many products fall into each segment*/

 select top 3 * from gold.dim_products;

WITH segments AS(
 select product_key,
 cost, 
 CASE 
 WHEN cost<100 THEN 'Below 100'
 WHEN cost BETWEEN 100 AND 500 THEN '100-500'
 WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
 ELSE 'Above 1000'
 End AS cost_segments
from gold.dim_products
)
SELECT count(product_key) as no_of_products,
cost_segments from segments
group by cost_segments;

--------using subquery-------
select count(product_key),cost_segments from

(select product_key,
 cost, 
 CASE 
 WHEN cost<100 THEN 'Below 100'
 WHEN cost BETWEEN 100 AND 500 THEN '100-500'
 WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
 ELSE 'Above 1000'
 End AS cost_segments
from gold.dim_products)t
group by cost_segments;


/*------vip:if customers have spent atleast 12 months and more than $5000
-------Regular:if customers have spent atleast 12 months and less than or equal $5000
-----New:customers with lifespan lessthan 12 months
---count customers who fall into the above categories---*/
WITH customer_segments AS(

select c.customer_key,
sum(f.sales_amount) as total_sales,
DATEDIFF(Month,Min(f.order_date),Max(f.order_date)) as life_span
from gold.fact_sales f LEFT JOIN gold.dim_customers c on f.customer_key=c.customer_key
group by c.customer_key
)
select count(customer_key) as total_customers,customer_segment from (
select customer_key,
total_sales,
life_span,
CASE WHEN life_span>=12 and total_sales>5000 THEN 'VIP'
     WHEN life_span>=12 and total_sales<=5000 THEN 'Regular'
	  ELSE 'NEW'
	  END AS customer_segment from customer_segments)t

	  group by customer_segment;




 SELECT TOP 3 * from gold.dim_customers;
select TOP 3 * from gold.dim_products;
select Top 3 * from gold.fact_sales;
	  




